# name: Deploy to VPS (frontend + dev + nginx)

# on:
#   push:
#     branches:
#       - '**' 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 🔐 Setup SSH agent
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: ${{ secrets.MINIAPP_KEY }}

#       - name: Add SSH host key to known_hosts
#         run: |
#           mkdir -p ~/.ssh
#           ssh-keyscan -H 45.9.40.96 >> ~/.ssh/known_hosts

#       - name: 🚀 SSH into server and deploy
#         run: |
#           BRANCH=${{ github.ref_name }}

#           ssh root@45.9.40.96 << EOF
#             set -e

#             echo "🌿 Current branch: $BRANCH"

#             echo "🧹 Cleaning docker cache"
#             docker builder prune -f
#             docker system prune -f
#             if [ "$BRANCH" = "main" ]; then

#               echo "🚀 Deploy PROD (frontend)"
              
#               cd /root/miniApp
#               git fetch origin
#               git checkout -B $BRANCH origin/$BRANCH
#               git pull 
#               cd /root
#               docker compose build --no-cache frontend
#               docker compose up -d frontend

#             elif [[ "$BRANCH" == sprint* ]]; then
#               echo "🚀 Deploy DEV (developing)"
              
#               cd /root/miniApp_dev
#               git fetch origin
#               git checkout -B $BRANCH origin/$BRANCH
#               git pull 

#               cd /root
#               docker compose build --no-cache developing
#               docker compose up -d developing

#             else
#               echo "⚠️ Branch '$BRANCH' ignored"
#             fi

#             echo "✅ Deployment finished!"
#           EOF

